# Generated by Django 4.0.1 on 2024-01-10 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TIENDA', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clasenatacion',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='clase_imagenes/'),
        ),
    ]
