# Generated by Django 4.0.1 on 2024-01-12 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TIENDA', '0007_remove_inscripcionclase_clase_comprada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprasclase',
            name='cupos_disponibles_pagos',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
