# Generated by Django 4.0.1 on 2024-02-24 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TIENDA', '0008_comprasclase_cupos_disponibles_pagos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('resumen', models.TextField()),
                ('contenido', models.TextField()),
                ('imagen', models.ImageField(upload_to='noticias/')),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
