# Generated by Django 4.0.1 on 2024-01-11 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USUARIOS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cupos_disponibles_pagos',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
